repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.2
  hooks:
  - id: terraform_fmt
    args:
    - --args=-diff
  - id: terraform_tflint
    args:
    - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl
    files: ^modules/
  - id: terraform_docs
    args:
    - --args=--config=.terraform-docs.yml
