formatter: "markdown table"

sections:
  show:
    - modules
    - resources
    - requirements
    - providers
    - inputs
    - outputs

sort:
  enabled: true
  by: required

settings:
  default: false
  lockfile: false

output:
  file: README.md
  mode: inject
